# Пример конфигурационного файла для приложения
# Это файл можно использовать как шаблон для создания собственного config.yaml

# Основные настройки приложения
app:
  # Имя приложения
  name: "MyApp"
  
  # Окружение (development, test, staging, production)
  env: "development"
  
  # Уровень логирования (debug, info, warn, error)
  log_level: "debug"
  
  # Версия приложения
  version: "1.0.0"

# Настройки сервера
server:
  # Хост, на котором запускаем сервер
  host: "localhost"
  
  # Порт сервера
  port: 8080
  
  # Таймауты чтения и записи
  read_timeout: "5s"
  write_timeout: "10s"
  
  # Включение/выключение режима отладки
  debug: true
  
  # Максимальный размер запроса в мегабайтах
  max_request_size_mb: 10
  
  # CORS настройки
  cors:
    # Разрешенные источники
    allowed_origins:
      - "http://localhost:3000"
      - "https://example.com"
    
    # Разрешенные методы
    allowed_methods:
      - "GET"
      - "POST"
      - "PUT"
      - "DELETE"
      
    # Разрешенные заголовки
    allowed_headers:
      - "Content-Type"
      - "Authorization"
      
    # Время жизни предварительных запросов в секундах
    max_age: 86400

# Настройки базы данных
database:
  # Хост базы данных
  host: "localhost"
  
  # Порт базы данных
  port: 5432
  
  # Имя пользователя
  username: "postgres"
  
  # Пароль (в реальном приложении лучше использовать переменные окружения)
  password: "password"
  
  # Имя базы данных
  name: "myapp"
  
  # Использование SSL
  ssl: false
  
  # Таймаут соединения в секундах
  timeout: 10
  
  # Максимальное количество соединений в пуле
  max_connections: 20
  
  # Время простоя соединения до закрытия
  idle_timeout: "5m"
  
  # Максимальное время жизни соединения
  max_lifetime: "1h"

# Настройки Redis
redis:
  # Хост Redis
  host: "localhost"
  
  # Порт Redis
  port: 6379
  
  # Пароль (если используется)
  password: ""
  
  # Индекс базы данных
  db: 0
  
  # Таймаут подключения в секундах
  timeout: 5
  
  # Максимальное количество простаивающих соединений
  max_idle: 10
  
  # Максимальное общее количество соединений
  max_active: 100

# Настройки аутентификации
auth:
  # Срок действия токена в минутах
  token_expiry: 60
  
  # Секрет для подписи JWT (в реальном приложении использовать переменные окружения)
  jwt_secret: "your-secret-key"
  
  # Алгоритм подписи JWT
  jwt_algorithm: "HS256"
  
  # Настройки хэширования паролей
  password:
    # Алгоритм хэширования
    algorithm: "bcrypt"
    
    # Стоимость (сложность) хэширования для bcrypt
    cost: 10

# Активные функциональности
features:
  - "auth"
  - "api"
  - "admin"
  - "metrics"

# Настройки для мониторинга и телеметрии
monitoring:
  # Включение Prometheus метрик
  enable_metrics: true
  
  # Путь для эндпоинта метрик
  metrics_endpoint: "/metrics"
  
  # Пороговые значения для предупреждений
  thresholds:
    # Максимальное время ответа в миллисекундах
    response_time_ms: 500
    
    # Порог для ошибок в процентах
    error_rate_percent: 1.0
    
    # Использование CPU в процентах
    cpu_usage_percent: 80.0
    
    # Использование памяти в процентах
    memory_usage_percent: 80.0 