CREATE TABLE users (
    user_id UUID PRIMARY KEY,
    user_name VARCHAR(255),
    user_email VARCHAR(320) UNIQUE NOT NULL,
    user_password VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);