app:
  name: "Example App"
  env: "development"
  log_level: "debug"
  version: "1.0.0"

server:
  host: "localhost"
  port: 8080
  read_timeout: "5s"
  write_timeout: "10s"
  debug: true

database:
  host: "localhost"
  port: 5432
  username: "example_user"
  password: "example_password"
  name: "example_db"
  ssl: false

features:
  - "auth"
  - "api"
  - "metrics" 